<?
	if($_SESSION['level']=='10') {
		$wiz_lan2=get_lang_file($ui_homepath.'/cgi_bank/notice/language'.$masterinfo['lang'].'.inc');
		$tarr=wizpath_encode($ui_pages);
		?>
		<div style="position:absolute;right:0;z-index:999;"><input type="button" class="ozbutton white small" value="<?=$wiz_lan2['setting']?>" onclick="window.open('/cgi_bank_wiz/html/html_1_config.php?cq=<?=base64_encode("422|$tarr[1]|$menu_id|71")?>','config','status=1,scrollbars=1,resizable=1,width=700,height=670');"></div>
		<?
	}
	?><div class="smartOutput htmlEditor float_clear"><p style="text-align: center;"><strong><span style="font-family:_오성과한음B;"><span style="font-size:36px;">특강 참여안내</span></span></strong></p>

<p style="text-align: center;">&nbsp;</p>

<table align="center" border="0" cellpadding="15" cellspacing="3" style="background-color:#99cc99;border-spacing:3px;width:70%;">
	<tbody>
		<tr>
			<td style="background-color: rgb(204, 255, 204); padding: 15px; text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">특강일</span></span></td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">2018년 7월 26일(목) 오후 7시 30분</span></span></p>
			</td>
		</tr>
		<tr>
			<td style="background-color: #ccffcc; padding: 15px;">
			<p style="text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">특강장소</span></span></p>
			</td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">역삼역에서 도보 5분 거리</span></span></p>

			<p><span style="font-size:18px;"><span style="font-family:_나눔스퀘어B;">* 신청하신 분에게 특강 전일에 자세한 약도를 보내드립니다.&nbsp;</span></span></p>

			<p><span style="font-size:18px;"><span style="font-family:_나눔스퀘어B;">*&nbsp; 지방에 계신 분은 따로 상담요청 부탁드립니다.</span></span></p>
			</td>
		</tr>
		<tr>
			<td style="background-color: #ccffcc; padding: 15px;">
			<p style="text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">특강비용</span></span></p>
			</td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">2만 원</span></span></p>
			</td>
		</tr>
		<tr>
			<td style="background-color: #ccffcc; padding: 15px;">
			<p style="text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">입금계좌</span></span></p>
			</td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">SC제일은행 245-20-072735 (사)국민독서인지문화원</span></span></p>
			</td>
		</tr>
		<tr>
			<td style="background-color: rgb(204, 255, 204); padding: 15px; text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">진행절차</span></span></td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">1. 신청 후&nbsp;바로 입금&nbsp;</span></span></p>

			<p><span style="font-family:_나눔스퀘어B;"><span style="color:#e67e22;"><span style="font-size:18px;">신청자와 입금자 동일해야 합니다.</span></span><span style="font-size:20px;"> </span><span style="font-size:18px;"><span style="font-size:20px;">-&nbsp;</span>신청자와 입금자가 다를 때는&nbsp;<span style="font-family:_나눔스퀘어B;"><span style="font-size:18px;">(070-4477-6631)로&nbsp;</span></span>연락 부탁 드립니다. 미연락 시 명단에서 누락될 수 있습니다.&nbsp;</span></span></p>

			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">2. 입금 확인 후&nbsp;이후 방법&nbsp;안내 문자 발송</span></span></p>

			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">3. 영상 수강 후 현장 참여</span></span></p>
			</td>
		</tr>
		<tr>
			<td style="background-color: #ccffcc; padding: 15px;">
			<p style="text-align: center;"><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;">진행기관</span></span></p>
			</td>
			<td style="background-color: rgb(255, 255, 255); padding: 15px;">
			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;"></span></span></p>

			<ul>
				<li><span style="font-size:22px;"><span style="font-family:_나눔스퀘어B;">주최 : (사)국민독서인지문화원&nbsp;부설 온리원교육연구소</span></span></li>
				<li><span style="font-size:22px;"><span style="font-family:_나눔스퀘어B;">주관 : 국제인지코치협회,&nbsp;</span></span><span style="font-size:22px;"><span style="font-family:_나눔스퀘어B;">대한신학대학원 인지코칭학</span></span></li>
			</ul>

			<p><span style="font-family:_나눔스퀘어B;"><span style="font-size:22px;"></span></span></p>
			</td>
		</tr>
	</tbody>
</table>

<p style="text-align: center;">&nbsp;</p>

<p>&nbsp;</p>
</div>