<?
	if($_SESSION['level']=='10') {
		$wiz_lan2=get_lang_file($ui_homepath.'/cgi_bank/notice/language'.$masterinfo['lang'].'.inc');
		$tarr=wizpath_encode($ui_pages);
		?>
		<div style="position:absolute;right:0;z-index:999;"><input type="button" class="ozbutton white small" value="<?=$wiz_lan2['setting']?>" onclick="window.open('/cgi_bank_wiz/html/html_1_config.php?cq=<?=base64_encode("43662|$tarr[1]|$menu_id|42")?>','config','status=1,scrollbars=1,resizable=1,width=700,height=670');"></div>
		<?
	}
	?><div class="smartOutput htmlEditor float_clear"><h1 class="oz_txt_h1" style="text-align: center;"><span style="font-size:20px;"><span style="font-family:나눔펜체;"></span></span><span style="color:#2980b9;"><strong>온리원 셀링플래너 교육</strong></span></h1>

<p id="SE-95d361e5-b303-4911-acb2-c52e528d3ccd">​</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<blockquote>
<h4 id="SE-9dab4f80-e60a-4181-b256-89f52f3bfe37"><span style="color:#27ae60;"><b>교육배경</b></span></h4>
</blockquote>

<p id="SE-d50de882-4e1e-4dc9-8fa9-fe1ee25e129a" style="margin-left: 40px;"><span style="font-size:17px;">1. 4차산업시대에 안정적인 직업창출의 필요</span></p>

<p id="SE-ecaa91b4-b943-4173-baa6-e75ccf8c4b53" style="margin-left: 40px;"><span style="font-size:17px;">2. 전문역량을 셀링할 수 있는 셀링역량 개발의 필요</span></p>

<p id="SE-69d6526f-7727-428b-8b21-526a8dfc2cfe" style="margin-left: 40px;"><span style="font-size:17px;">3. 모바일기반 종합마케팅을 통한 셀링전문가 양성의 필요</span></p>

<p id="SE-92cf7c61-897d-4c18-b23c-3a7110e641f4" style="margin-left: 40px;"><span style="font-size:17px;">4. 홍보대행의 의뢰가 많아짐이 예상되므로 전문 셀링플래너 양성의 필요</span></p>

<p id="SE-5dbebf06-8d0a-461a-8a66-298de1af3a58">​</p>

<p>&nbsp;</p>

<blockquote>
<h4 id="SE-d845914d-ed73-4527-bbff-7063db3fb2d2"><span style="color:#27ae60;"><b>교육목표</b></span></h4>
</blockquote>

<p id="SE-c08c408c-a45a-4aa6-a922-6c186a3dcad9" style="margin-left: 40px;"><span style="font-size:17px;">종합마케팅에 능한 셀링전문가 양성으로 새로운 일자리 창출 및 소상공인의 매출증진에 기여한다.</span></p>

<p>&nbsp;</p>

<p id="SE-fd0b962b-1d03-4564-b5fd-84ba297883ae">​</p>

<blockquote>
<h4 id="SE-bc2c4157-9ebd-4628-b701-0fac2323138c"><span style="color:#27ae60;"><b>교육특징</b></span></h4>
</blockquote>

<p id="SE-52d1b113-648f-49c4-8387-8109f493fba2" style="margin-left: 40px;"><span style="font-size:17px;">모바일 기반 종합적 마케팅에 대한 습득 및 실전에 바로 활용</span></p>

<p>&nbsp;</p>

<p id="SE-5bb5a417-d86f-4d5f-afa6-b8bc53c99acb">​</p>

<blockquote>
<h4 id="SE-d6705742-e283-4024-a2c3-bda27571efe7"><span style="color:#27ae60;"><b>교육대상</b></span></h4>
</blockquote>

<p id="SE-e178b4e3-c870-4101-82f7-1ac2a947d6ed" style="margin-left: 40px;"><span style="font-size:17px;">∎ 정부지원금 받아 매출 증진을 하고 싶은 분</span></p>

<p id="SE-017b604d-e7c4-4465-bb68-8a3374997229" style="margin-left: 40px;"><span style="font-size:17px;">∎ 정부지원금 받아 창업 및 홍보대행사업을 하고 싶은 분</span></p>

<p id="SE-8f331a2b-6761-40ff-93cd-175567d161f7" style="margin-left: 40px;"><span style="font-size:17px;">∎ 오랫동안 영업 및 판매로 힘들어 하고 있는 분</span></p>

<p id="SE-30c1613c-3f69-47d5-b361-ea82ad3a61ae" style="margin-left: 40px;"><span style="font-size:17px;">∎ 직장 및 개인사업을 하면서 투잡을 하고 싶은 분</span></p>

<p id="SE-4282df71-a463-4dc7-8d0b-2424eec5bc35" style="margin-left: 40px;"><span style="font-size:17px;">∎ 자신의 상품을 홍보플랜유통하고 싶은 분</span></p>

<p id="SE-0d1878f3-d25a-4788-9adb-c478fb841daf" style="margin-left: 40px;"><span style="font-size:17px;">∎ 소상공인의 GOOD상품 소개하고 싶은 분</span></p>

<p id="SE-26c10c91-8039-432f-ad9d-2d9104b78460" style="margin-left: 40px;"><span style="font-size:17px;">∎ 디지털 노마드 생활을 꿈꾸는 분</span></p>

<p>&nbsp;</p>

<p id="SE-7015b05c-fd9a-4e5f-96c2-938e842be02a">​</p>

<blockquote>
<h4 id="SE-011cc2c2-d5cc-4dc5-8166-a12bfe03b30b"><span style="color:#27ae60;"><b>교육일정</b></span></h4>
</blockquote>

<p id="SE-935e7c33-a477-4d67-82f1-639a8443c2e8" style="margin-left: 40px;"><span style="font-size:17px;">1. 교육시간 : 16시간, 4시간씩 4일</span></p>

<p id="SE-96ec805b-0800-44b0-a0ab-c7cd0c08dc06" style="margin-left: 40px;"><span style="font-size:17px;">2. 교육일시 : 화, 금 오후 3 ~ 7시</span></p>

<p id="SE-995f3344-be99-4d74-a800-150f5ad22386" style="margin-left: 40px;"><span style="font-size:17px;">3. 교육기간 : 매월 1-2주, 3-4주</span></p>

<p id="SE-93c03e13-34b7-49c6-97ea-20af247c5e3d" style="margin-left: 40px;"><span style="font-size:17px;">4.&nbsp;<b>1기 시작 : 2019년 8월 27일(화)</b></span></p>

<p>&nbsp;</p>

<p id="SE-0c4aeee8-85dc-43ef-95e5-0d15bba5796b">​</p>

<blockquote>
<h4 id="SE-9a12f865-62d5-449c-bf0b-2fe024db6490"><span style="color:#27ae60;"><b>교육참여형태</b></span></h4>
</blockquote>

<p id="SE-ee5aee0a-1040-4198-a5ed-ef90e45d9e2e" style="margin-left: 40px;"><span style="font-size:17px;">1. 현장참여(노트북 지참)</span></p>

<p id="SE-c8948f94-fd12-44ee-8fb7-fd9f627f78b8" style="margin-left: 40px;"><span style="font-size:17px;">2. 화상참여(실시간 온라인 참여)</span></p>

<p id="SE-c42910b0-b2ac-421e-a09f-bc95b5494ca4" style="margin-left: 40px;"><span style="font-size:17px;">3. 영상참여(영상 사이트 시청)</span></p>

<p>&nbsp;</p>

<p id="SE-dfcef41c-950f-463c-a4eb-561cf7d9e11f">​</p>

<blockquote>
<h4 id="SE-8fd37298-cf14-4d0e-b881-b6572e9c323f"><span style="color:#27ae60;"><b>교육내용</b></span></h4>
</blockquote>

<p id="SE-7815d8b3-d0b9-4e4d-af36-cb639ee61c66" style="margin-left: 40px;"><span style="font-size:17px;">1. 온리원역량의 이해</span></p>

<p id="SE-09560cbe-ecfc-4ac8-8061-30b55ebe969f" style="margin-left: 40px;"><span style="font-size:17px;">2. 셀링플랫폼 시장 이해</span></p>

<p id="SE-da45e52b-8ad1-4697-afa7-41b2dea0c46d" style="margin-left: 40px;"><span style="font-size:17px;">3. 최근 마케팅의 이해</span></p>

<p id="SE-8aeef540-9c9d-4ed8-bbe6-395f39fcc940" style="margin-left: 40px;"><span style="font-size:17px;">4. 1인 셀링플랫폼 활용(디버, 카피, 예약, 발송, 관리)</span></p>

<p id="SE-35431cac-96dc-49a0-a154-2150247215ae" style="margin-left: 40px;"><span style="font-size:17px;">5. 상품선정과 쇼핑몰 코칭</span></p>

<p id="SE-3a4a20a7-2265-4442-8d14-fca0a8c53fa6" style="margin-left: 40px;"><span style="font-size:17px;">6. 다중자동 예약기능 코칭(이벤트, 랜딩, 링크, 예약, 관리)</span></p>

<p id="SE-4154a3ed-035d-49aa-8ab3-c46249e7bbdf" style="margin-left: 40px;"><span style="font-size:17px;">7. 메시지카피와 발송 코칭</span></p>

<p id="SE-596f8926-66d6-4257-9d73-9ff86d3c6d52" style="margin-left: 40px;"><span style="font-size:17px;">8. 회신고객관리 코칭</span></p>

<p id="SE-8b877e1c-9d31-45e6-b8ba-377c9332f166" style="margin-left: 40px;"><span style="font-size:17px;">9. 셀링과정 실습 코칭</span></p>

<p>&nbsp;</p>

<p id="SE-54a747f3-6c39-4aa5-9063-850ed6ede730">​</p>

<blockquote>
<h4 id="SE-ea6919b0-a044-40ce-b6ee-d5408e4505ac"><span style="color:#27ae60;"><b>교육비용</b></span></h4>
</blockquote>

<p id="SE-fed331c3-68c4-471a-8a35-1c31617397fa" style="margin-left: 40px;"><span style="font-size:17px;">1. 교육비용 : 55만원(현장/화상/영상 동일)</span></p>

<p id="SE-384722b9-94d1-48d2-a26f-ff354e4efbf8" style="margin-left: 40px;"><span style="font-size:17px;">2. 사업용구매자 :&nbsp;<b>50%할인(교육 1기 신청자 대상 이벤트)</b></span></p>

<p id="SE-d4e4fa14-3bac-45c4-82de-ab4531f33972" style="margin-left: 40px;"><span style="font-size:17px;">3. 종합용구매자 : 무료</span></p>

<p id="SE-2eecf90b-088c-459c-9448-03313304cfd2" style="margin-left: 40px;"><span style="font-size:17px;">4. 입금계좌 :&nbsp;스텐다드차타드은행 617-20-109431 온리원연구소 (구,SC제일은행)</span></p>

<p>&nbsp;</p>

<p id="SE-7e0a49bf-3a02-42fc-996c-7b96f3d13e45">​</p>

<blockquote>
<h4 id="SE-71f85c2b-1d81-4031-967d-afa8aca5027f"><span style="color:#27ae60;"><b>교육이후 활동</b></span></h4>
</blockquote>

<p id="SE-5b040d3d-a2f4-4e96-b414-18733fa5b41a" style="margin-left: 40px;"><span style="font-size:17px;">1. 자기사업에서 활용</span></p>

<p id="SE-fcbdb98b-d00d-46bb-bf96-2bdc009ac914" style="margin-left: 40px;"><span style="font-size:17px;">2. 서민경제살리기국민연합(서경련) 회원 활동</span></p>

<p id="SE-6bfada0b-48fd-47ce-9754-e6f5ae3bff38" style="margin-left: 40px;"><span style="font-size:17px;">3. 온리원 셀링플래너(SP)로 등록</span></p>

<p id="SE-c9eba97b-fdfb-4016-b566-3190006a67f7" style="margin-left: 40px;"><span style="font-size:17px;">4. 서경련 사업체 SP활동</span></p>

<p>&nbsp;</p>

<p id="SE-a63dada2-584d-4acd-987f-3aecc9603864">​</p>

<blockquote>
<h4 id="SE-6d849a34-cc82-4bb1-a4ae-5250ef44cfe1"><span style="color:#27ae60;"><b>환불 규정</b></span></h4>
</blockquote>

<p id="SE-77f6e919-b65f-47ae-9d83-14a653e9cc35" style="margin-left: 40px;"><span style="font-size:17px;">* 강의 첫 번째 회차 시작하는 당일로부터 5일 전 : 수강료 전액 환불</span></p>

<p id="SE-963dbd50-c79f-4579-ad18-7d8d04d21913" style="margin-left: 40px;"><span style="font-size:17px;">* 강의 첫 번째 회차 시작하는 당일로부터 4일 전~2일 전 : 해당 금액의 50% 환불</span></p>

<p id="SE-165c4f20-6e33-4424-a5f5-fb95d6c2342a" style="margin-left: 40px;"><span style="font-size:17px;">* 강의 1일 전, 그 이후의 환불은 불가능합니다.</span></p>

<p id="SE-96058f58-bb9f-4e8d-82b8-21cca8182c16" style="margin-left: 40px;"><span style="font-size:17px;">* 환불처리는 환불 신청일 기준으로 24시간 이내 처리됩니다.</span></p>

<p style="margin-left: 40px;">&nbsp;</p>

<p id="SE-018dbf0d-6471-40c1-a08a-560fd178e2b7" style="margin-left: 40px;">​</p>

<blockquote>
<h4 id="SE-bc646f59-5dde-42e8-97e1-d1a93cf53186"><span style="color:#27ae60;"><b>교육장소</b></span></h4>
</blockquote>

<p id="SE-155b4b55-5f30-4f5a-9ed3-2d1e5e69a4d3" style="margin-left: 40px;"><span style="font-size:17px;">온리원마케팅연구소</span></p>

<p id="SE-ec7547ad-ffb4-4f67-bf8f-437e6c95aae6" style="margin-left: 40px;"><span style="font-size:17px;">서울 영등포구 영중로 159 우송빌딩 4층(1층에 농협있는 건물)</span></p>

<p id="SE-aea8aa68-cd42-4701-a765-7622fab599c5" style="margin-left: 40px;"><span style="font-size:17px;">당산역 9번 출구 / 도보 5분</span></p>

<p style="text-align: center;"><span style="font-size:18px;"><span style="font-family:나눔펜체;"><span style="color:#c0392b;"></span></span></span></p>
</div>