<?
	if($_SESSION['level']=='10') {
		$wiz_lan2=get_lang_file($ui_homepath.'/cgi_bank/notice/language'.$masterinfo['lang'].'.inc');
		$tarr=wizpath_encode($ui_pages);
		?>
		<div style="position:absolute;right:0;z-index:999;"><input type="button" class="ozbutton white small" value="<?=$wiz_lan2['setting']?>" onclick="window.open('/cgi_bank_wiz/html/html_1_config.php?cq=<?=base64_encode("5454|$tarr[1]|$menu_id|42")?>','config','status=1,scrollbars=1,resizable=1,width=700,height=670');"></div>
		<?
	}
	?><div class="smartOutput htmlEditor float_clear"><p style="text-align: center;"><span style="font-size:20px;"><span style="font-family:나눔펜체;">교회성장의 감소가 고민이 되고 있는 이때!</span></span></p>

<p style="text-align: center;"><span style="font-size:20px;"><span style="font-family:나눔펜체;">교회성장의 혁신적인 솔루션을 개발하여 목사님들에게 선보이고자 설명회에 초대합니다.</span></span></p>

<p style="text-align: center;">&nbsp;</p>

<p><span style="font-family:_나눔스퀘어L;"></span></p>

<p style="text-align: center;"><span style="font-family:_나눔스퀘어L;"><span style="font-size:24px;"><strong>┌&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></span></span></p>

<p style="text-align: center;"><span style="font-family:_나눔스퀘어L;"></span></p>

<p style="text-align: center;"><span style="font-family:_나눔스퀘어EB;"><span style="font-size:24px;"><strong>AI시대 교회성장 솔루션 무료강연</strong></span></span></p>

<p style="text-align: center;"><span style="font-family:_나눔스퀘어EB;"><span style="font-size:24px;"><strong>초대안내</strong></span></span></p>

<p style="text-align: center;"><span style="font-family:_나눔스퀘어L;"><span style="font-size:24px;"><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ┘</strong></span></span></p>

<p style="text-align: center;">&nbsp;</p>

<p><span style="font-family:_나눔스퀘어L;"></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">1. 일시 : 매주 월요일 오후2시</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">2. 장소 : 온리원마케팅연구소</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">3. 비용 : 무료</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">4. 대상 : 목회자, 장로</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">5. 주제 : AI시대 교회성장 솔루션을 제시하다!</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">6. 강의 : 온리원마케팅연구소 수석연구원</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">7. 주관 : 온리원마케팅연구소</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;">8. 신청 : 문자로 부탁드립니다.</span></span></p>

<p><span style="font-size:20px;"><span style="font-family:나눔펜체;"></span></span></p>

<p style="text-align: center;"><span style="font-size:18px;"><span style="font-family:나눔펜체;"><span style="color:#c0392b;">(당일 참석이 어려우신 분은 문의 주시면 개별 미팅 및 체험이 가능합니다.)</span></span></span></p>
</div>